package.json, webapp/description/description.js, webapp/descriptionBundles/dataSourceDescriptionAndComments.js, webapp/descriptionBundles/generalComments.js, webapp/reusableUiComponents/icon.js, webapp/tableWithOdp/tableWithOdp.js, webapp/traditionalTable/actions.js, webapp/traditionalTable/traditionalTable.js
Remove unnecessary dependency 'assert'.
Use package 'prop-types' in most cases.
=> Remove assert

webapp/admin/adminView.js, webapp/admin/components/usersCount.js, webapp/header/header.js, webapp/landing/landingView.js, webapp/landing/style.less, webapp/loggedin/loggedInView.js, webapp/loggedin/routes.js
Added some nested routing.
Should generate common component from links menu, both (all?) behave the same way.
=> Nested routing

server/assessment/service/csvOutput.js, server/assessment/service/csvOutputWithVariables.js, server/panEuropean/panEuropeanRepository.js
https://github.com/date-fns/date-fns/blob/master/docs/unicodeTokens.md
=> date-fns: YYYY -> yyyy, DD -> dd

webapp/countryMessageBoard/countryMessageBoardView.js
Use `messageContainerEl.scrollHeight` instead of `messageContainerRef.scrollHeight`
=> fix scrolling issue in chat

webapp/components/definitionLink.js
Fixes broken definitions and faq links
=> Fix definitions link

webapp/app/actions.js, webapp/loggedin/navigation/actions.js, webapp/loggedin/review/actions.js, webapp/loggedin/userChat/actions.js, webapp/originalDataPoint/actions.js
Use always dispatch(fn()) and not fn()(dispatch)
=> Actions Dispatch

webapp/loggedin/routes.js
Move .../:odpId higher in hiearchy
=> National Data Point data loading problem

webapp/landing/landingView.js, webapp/loggedin/navigation/components/assessment.js
Updated assessment menu (left drawer) and landingview sub menu (top right) to use NavLink
=> Use NavLink for menus

webapp/loggedin/navigation/components/assessment.js
Fixes error in console about key prop
=> assessment: no key prop, use vanilla map

webapp/app/appRouterSwitch.js, webapp/app/appState.js, webapp/app/reducer.js, webapp/components/loading.js, webapp/user/actions.js
Display the Tucan bird on page refresh (when userInit has not yet ran)
=> General: Display 'Loading' before userInit done

webapp/app/assessment/panEuropean/sections/indicators/panEuropeanIndicatorsView.js
=> panEuropeanIndicatorsView.js: fixed visualization in public view

server/panEuropean/panEuropeanApi.js, webapp/app/assessment/panEuropean/sections/indicators/panEuropeanIndicatorsView.js
=> panEuropeanIndicatorsView.js: removed reviewIndicator in public view

webapp/app/assessment/fra/sections/originalDataPoint/components/commentsEditor.js, webapp/app/assessment/fra/sections/originalDataPoint/originalDataPointView.js
commentsEditor component as functional component
=> commentsEditor: functional components

server/auth/authApiMiddleware.js, server/utils/requestUtils.js
=> Allow GET methods

server/auth/resetPassword.js, webapp/login/components/resetPasswordForm.js, webapp/login/loginView.js
=> fix reset password

webapp/login/loginView.js
=> exact path login

common/assessment/fra.js, webapp/app/assessment/assessmentStateValidator.js, webapp/app/assessment/components/dataTable/table/cell/cell.js, webapp/app/assessment/components/dataTable/table/cell/useCellClassName.js, webapp/app/assessment/components/section/sectionSpec/colSpec.js, webapp/app/assessment/components/section/sectionSpecs.js, webapp/app/assessment/fra/sections/forestAreaWithinProtectedAreas/forestAreaWithinProtectedAreasValidatorState.js, webapp/app/assessment/fra/sections/forestAreaWithinProtectedAreas/sectionSpec.js
=> Table 3b: added section spec

webapp/userManagement/edit/editUserForm.js, yarn.lock
=> User edit: fixed edit user role

common/assessment/fra.js, webapp/app/assessment/components/section/sectionSpecs.js, webapp/app/assessment/fra/sections/annualReforestation/annualReforestationValidatorState.js, webapp/app/assessment/fra/sections/annualReforestation/sectionSpec.js
=> refactor table 1d

common/assessment/fra.js, common/fraUtils.js, webapp/app/assessment/components/section/sectionSpecs.js, webapp/app/assessment/fra/sections/extentOfForest/extentOfForestState.js, webapp/app/assessment/fra/sections/otherLandWithTreeCover/otherLandWithTreeCoverState.js, webapp/app/assessment/fra/sections/otherLandWithTreeCover/otherLandWithTreeCoverValidatorState.js, webapp/app/assessment/fra/sections/otherLandWithTreeCover/sectionSpec.js, webapp/app/assessment/fra/sections/specificForestCategories/sectionSpec.js
=> Table 1f: added section spec

webapp/app/assessment/fra/sections/forestCharacteristics/forestCharacteristicsState.js, webapp/app/assessment/fra/sections/specificForestCategories/sectionSpec.js, webapp/app/assessment/fra/sections/specificForestCategories/specificForestCategoriesValidatorState.js
=> Table 1e: added primary forest validator

webapp/app/assessment/components/section/components/descriptions/components/components/title.js
Resolves #197 
Use defaultProp value for error
=> description/title: FIX: error as defaultProp

server/odp/api.js, webapp/app/assessment/fra/sections/originalDataPoint/actions/actions.js, webapp/app/assessment/fra/sections/originalDataPoint/actions/updateSectionTables.js, webapp/app/assessment/fra/sections/originalDataPoint/originalDataPointView/components/buttonBar.js
=> odp actions: use history not window.location

webapp/app/assessment/fra/sections/extentOfForest/actions.js, webapp/app/assessment/fra/sections/extentOfForest/extentOfForestState.js, webapp/app/assessment/fra/sections/originalDataPoint/originalDataPointView/components/yearSelection.js, webapp/app/assessment/fra/sections/originalDataPoint/originalDataPointView/originalDataPointView.js
=> yearSelection: disable existing odp years in odp view (#220)

webapp/app/assessment/components/dataTable/chart/chartContainer.js, webapp/app/assessment/components/dataTable/chart/useChartData.js, webapp/main/routes.js
=> Chart: removed placeholder in print view

.eslintignore, .gitignore, .prettierignore, server/user/userApi.js, webapp/app/admin/components/versioning/NewVersionForm.js, webapp/app/admin/components/versioning/VersioningViewTable.js, webapp/app/components/header/components/userInfo.js, webapp/app/routes.js, webapp/main/basePaths.js, webapp/main/routes.js
=> Fix admin paths

webapp/app/assessment/components/dataTable/actions/generate.js, webapp/app/assessment/components/dataTable/actions/index.js, webapp/app/assessment/components/dataTable/actions/read.js, webapp/app/assessment/components/dataTable/actions/update.js
This is just a refactor of data table actions; preliminary for implementing paste values.
=> Split data table actions into sub modules

webapp/app/assessment/components/dataTable/actions/persist.js, webapp/app/assessment/components/dataTable/actions/update.js, webapp/app/assessment/components/dataTable/table/row/rowData/cell/cell.js, webapp/app/assessment/components/dataTable/table/row/rowData/cell/number.js, webapp/app/assessment/components/dataTable/table/row/rowData/cell/select.js, webapp/app/assessment/components/dataTable/table/row/rowData/cell/text.js, webapp/app/assessment/components/dataTable/table/row/rowData/cell/useOnChange.js, webapp/app/assessment/components/section/sectionSpec/colSpec.js, webapp/app/assessment/components/section/sectionSpec/index.js, webapp/app/assessment/components/section/sectionSpec/keysType.js, webapp/app/assessment/components/section/sectionSpec/rowSpec.js, webapp/app/assessment/components/section/sectionSpec/tableSpec.js, webapp/app/assessment/fra/sections/forestAreaChange/actions.js, webapp/app/assessment/fra/sections/growingStock/actions.js, webapp/app/assessment/fra/sections/growingStock/growingStockState.js
Resolves #232, resolves #233, resolves #234
=> Added Paste values with Sanitizer for dataTables

common/bignumberUtils.js, webapp/app/assessment/assessmentStateValidator.js, webapp/app/assessment/fra/sections/extentOfForest/extentOfForestValidatorState.js, webapp/app/assessment/fra/sections/otherLandWithTreeCover/otherLandWithTreeCoverValidatorState.js, webapp/app/assessment/fra/sections/specificForestCategories/specificForestCategoriesValidatorState.js
=> NumberUtils: added greaterThanWithTolerance

common/fraUtils.js, webapp/app/assessment/components/dataTable/dataTable.js, webapp/app/assessment/components/dataTable/table/table.js
=> PrintView: hide chart when data is empty

.travis.yml, package.json
=> Release strategy update

server/user/userApi.js, server/user/userRepository.js, webapp/app/user/userManagement/edit/editUserForm.js
=> Fixed user edit with no country selection

webapp/app/assessment/components/print/style.less, webapp/app/assessment/components/section/components/descriptions/components/generalComments.js, webapp/app/assessment/fra/sections/originalDataPoint/nationalDataPointsPrintView.js
=> PrintView: update ODPs and generalComments style

webapp/app/appView.less
=> Safari bug: appView: use calc() instead of fr

webapp/app/components/navigation/components/assessment/header/titleAssessment.js
=> fix navigation layout

webapp/app/components/navigation/components/assessment/section/navigationLink.js, webapp/app/dataExport/dataExport.js, webapp/main/basePaths.js
=> dataExport: redirect to first item on /export/

webapp/app/dataExport/useDataExportState.js
Resolves #277
Note: New api endpoint for fetching country list has not been added in this pull request
=> useDataExportState: initial commit

common/i18n/resources/en.js, server/country/api.js, webapp/app/appView.js, webapp/app/dataExport/countrySelect/countrySelect.js, webapp/app/dataExport/countrySelect/countrySelect.less, webapp/app/dataExport/countrySelect/index.js, webapp/app/dataExport/dataExport.js, webapp/app/dataExport/dataExport.less, webapp/app/dataExport/useDataExportState.js, webapp/main/basePaths.js
=> Data Export: Country selection

server/apiRouter.js, server/dataExport/api.js, server/dataExport/dataExportRepository.js
=> dataExport api: initial commit

common/assessment/panEuropean.js, common/i18n/resources/en.js, server/traditionalTable/mappings/panEuropean/index.js, server/traditionalTable/mappings/panEuropean/table1_1a.js, server/traditionalTable/tableMappings.js, webapp/app/assessment/components/section/fra.js, webapp/app/assessment/components/section/panEuropean.js, webapp/app/assessment/components/section/sectionSpecs.js, webapp/app/assessment/panEuropean/sections/table_1_1a/sectionSpec.js
=> Pan European table 1.1a metadata

webapp/app/dataExport/dataExport.js, webapp/app/dataExport/useDataExportState.js
=> dataExport: added 'hasSelection', hide/display table on change

webapp/app/dataExport/components/resultsTable/resultsTable.js
=> resultsTable: render row without value

webapp/app/components/header/components/AppLinks.js
=> AppLinks: use hardcoded path to export view

common/i18n/resources/en.js, common/i18n/resources/es.js, common/i18n/resources/fr.js, common/i18n/resources/ru.js
=> i18n: 'Variable' => 'FRA Variable'

common/i18n/resources/en.js, common/i18n/resources/es.js, common/i18n/resources/fr.js, common/i18n/resources/ru.js, server/assessment/assessmentRepository.js, server/country/countryRepository.js, server/country/countryService.js, webapp/app/assessment/components/section/sectionSpec/unitSpec.js, webapp/app/dataExport/components/countrySelect/countrySelect.js, webapp/app/dataExport/components/resultsTable/resultsTable.js, webapp/app/dataExport/components/resultsTable/resultsTable.less, webapp/app/dataExport/utils/format.js, webapp/components/buttonCheckBox/buttonCheckBox.js, webapp/components/buttonCheckBox/buttonCheckBox.less
Resolves #334 
Resolves #331  
Resolves #326
=> Improvements for Data Export - timestamp, desk study

server/db/migration/migrations/sqls/20200604164503-statistical-factsheets-view-up.sql
- Removed labels from variables/row_names.
Resolves #357
=> statisticalFactsheets: update database view

common/i18n/resources/fr.js, webapp/app/assessment/fra/print/fraPrintView.js
=> Updated desk study french translation

common/assessment/assessment.js, common/i18n/resources/en.js, package.json, server/dataExport/dataExportRepository.js, server/serverInit.js, server/traditionalTable/api.js, server/traditionalTable/mappings/panEuropean/index.js, webapp/app/assessment/components/dataTable/actions/read.js, webapp/app/assessment/components/section/assessmentSectionView/assessmentSection.js, webapp/app/assessment/components/section/components/title/title.js, webapp/app/components/navigation/components/assessment/assessment.js, webapp/app/components/navigation/components/assessment/header/header.js, webapp/app/components/navigation/components/assessment/header/lock.js, webapp/app/components/navigation/components/assessment/header/status.js, webapp/app/components/navigation/components/assessment/header/title.js, webapp/app/components/navigation/components/assessment/section/navigationLink.js, webapp/app/components/navigation/components/assessment/section/section.js, webapp/app/components/navigation/components/assessment/section/section.less, webapp/app/components/navigation/navigation.js, webapp/app/dataExport/components/columnSelect/columnSelect.js, webapp/app/dataExport/components/countrySelect/countrySelect.js, webapp/app/dataExport/components/resultsTable/resultsTable.js, webapp/app/dataExport/useDataExportState.js, webapp/app/dataExport/utils/format.js, webapp/app/dataExport/utils/panEuropean.js, webapp/app/dataExport/utils/panEuropeanMappings.js, yarn.lock
=> Pan european/fix export and navigation

common/country/area.js, common/country/country.js, common/country/index.js, webapp/app/appView.less, webapp/app/components/countrySelection/components/countryList.js, webapp/app/components/countrySelection/components/countryListRoleSection.js, webapp/app/components/countrySelection/components/countryListRow.js, webapp/app/components/countrySelection/components/countrySelection.js, webapp/app/components/countrySelection/components/countrySelection.less, webapp/app/landing/landingView.js, webapp/main/styles/config.less
**No functionality has changed.**
Just to facilitate next code reviews
=> Made CountrySelection eslint compliant

common/country/area.js, webapp/app/components/countrySelection/components/countryList.js, webapp/app/components/countrySelection/components/countryList.less, webapp/app/components/countrySelection/components/countrySelection.js
=> countrySelection: added global and regions

webapp/app/components/navigation/navigation.js
=> Disable panEuropean navigation

webapp/app/statisticalFactsheets/ForestOwnership/ForestOwnership.js, webapp/app/statisticalFactsheets/PrimaryForest/PrimaryForest.js, webapp/app/statisticalFactsheets/utils/propUtils.js
=> Added safeProp in utils/propUtils

webapp/app/landing/landingView.js, webapp/main/basePaths.js, webapp/main/routes.js
=> Statistical Factsheets: Remove routes and hide tabs if region

common/i18n/resources/en.js, webapp/app/countryLanding/views/statisticalFactsheets/components/table/table.js
=> statisticalFactsheets/table: display empty rows

server/serverInit.js, webapp/app/landing/Introduction/Introduction.js, webapp/app/landing/Introduction/index.js, webapp/app/landing/Introduction/introduction.less, webapp/app/landing/landing.js, webapp/app/landing/landing.less
=> Home: added introduction section

webapp/components/buttonTableExport/buttonTableExport.js, webapp/components/buttonTableExport/utils.js
=> buttonTableExport: .csv filename, format to number if number

webapp/app/countryLanding/views/statisticalFactsheets/statisticalFactsheets.less
=> statisticalFactsheets.less: remove position relative

webapp/components/Header/Header.js, webapp/components/Header/components/autoSaveStatusText.js
=> header: hide autosave if in country root

server/db/migration/migrations/sqls/20200129121445-forest-characteristics-view-up.sql
=> Fixed forest_characteristics_view

webapp/app/countryLanding/views/statisticalFactsheets/PrimaryForest/PrimaryForest.js
=> Statistical factsheets: fixed PrimaryForest rendering when area is null

webapp/app/dataExport/useDataExportState.js
=> useDataExportstate: Sort countries by listName[language]

webapp/components/countrySelection/components/countrySelection.js
Fixes some issues with dropdown in country selection
=> countrySelection: hotfix open dropdown

common/country/area.js, common/i18n/resources/en.js, common/i18n/resources/es.js, common/i18n/resources/fr.js, common/i18n/resources/ru.js, server/assessment/api.js, server/assessment/service/annual/annualYearsExporter.js, server/assessment/service/csvOutputWithVariables.js, server/assessment/service/exportService.js, server/assessment/service/fraYears/fraYearsExporter.js, server/dataExport/api.js, webapp/app/components/navigation/navigation.js, webapp/app/components/navigation/navigation.less
=> Bulk download

server/serverInit.js
=> serverInit: add missing routes

server/db/migration/migrations/sqls/20200923094820-content-check-extent-view-up.sql
=> content-check-extent-view: fix yearS

server/dataExport/README.txt, server/dataExport/api.js, webapp/app/components/navigation/navigation.js
=> dataExport/bulkDownload: add README.txt

server/db/migration/migrations/sqls/20200923094820-content-check-extent-view-up.sql
=> migrations: content-check-extent-view-up fix invalid years to null

server/db/migration/migrations/20201009062825-content-check-forest-growing-stock-biomass-carbon.js, server/db/migration/migrations/sqls/20201009062825-content-check-forest-growing-stock-biomass-carbon-down.sql, server/db/migration/migrations/sqls/20201009062825-content-check-forest-growing-stock-biomass-carbon-up.sql
Adds missing migration for content check
=> migrations: added content_check_forest_growing_stock_biomass_carbon

webapp/app/components/navigation/components/assessment/section/section.js
=> navigation/section: sort keys

server/traditionalTable/mappings/panEuropean/table3_3.js, server/traditionalTable/mappings/panEuropean/table3_4.js, webapp/app/assessment/panEuropean/sections/table_3_3/sectionSpec.js, webapp/app/assessment/panEuropean/sections/table_3_4/sectionSpec.js
=> Pan European tables 3.3 & 3.4 metadata: category codes & names are printed

webapp/app/components/navigation/components/assessment/section/section.less
=> navigation: fix overflow issue

webapp/components/countrySelection/components/CountryListFra/CountryListFra.js, webapp/pages/Landing/Introduction/AreaSelector/AreaSelector.js
=> Hide forest europe

webapp/components/footer/components/sendFeedback.js, webapp/components/footer/footer.js
=> footer: Add send feedback when user not logged

webapp/app/dataExport/components/resultsTable/resultsTable.js
=> resultsTable: remove extra colSpan

web-resources/index.html
=> google-analytics: event tracking

server/dataExport/dataExportRepository.js, server/db/migration/migrations/20201124131843-primary-designated-management-objective-view.js, server/db/migration/migrations/sqls/20201124131843-primary-designated-management-objective-view-down.sql, server/db/migration/migrations/sqls/20201124131843-primary-designated-management-objective-view-up.sql
=> dataExport: 3a fix no_unknown variable missing data

common/i18n/resources/en.js, webapp/app/dataExport/components/variableSelect/variableSelect.js
=> dataExport/variableSelect: if panEuropean show 'Variable'

server/auth/authApi.js
Redirect back to home page after user login.
=> Fix issue in redirect after login

common/i18n/resources/en/statisticalFactsheets.js, server/country/countryRepository.js, server/db/migration/migrations/20201125122749-country-aggregate.js, server/db/migration/migrations/sqls/20200604164503-statistical-factsheets-view-up.sql, server/db/migration/migrations/sqls/20201125122749-country-aggregate-down.sql, server/db/migration/migrations/sqls/20201125122749-country-aggregate-up.sql, server/statisticalFactsheets/api.js, server/statisticalFactsheets/service.js, server/statisticalFactsheets/statisticalFactsheetsRepository.js, webapp/app/countryLanding/views/statisticalFactsheets/CarbonGrowingStock/CarbonGrowingStock.js, webapp/app/countryLanding/views/statisticalFactsheets/ForestArea/ForestArea.js, webapp/app/countryLanding/views/statisticalFactsheets/ForestAreaWithinProtectedAreas/ForestAreaWithinProtectedAreas.js, webapp/app/countryLanding/views/statisticalFactsheets/ForestOwnership/ForestOwnership.js, webapp/app/countryLanding/views/statisticalFactsheets/NaturallyRegeneratingForest/NaturallyRegeneratingForest.js, webapp/app/countryLanding/views/statisticalFactsheets/components/table/table.js, webapp/app/countryLanding/views/statisticalFactsheets/hooks/useStatisticalFactsheetsState.js, webapp/app/countryLanding/views/statisticalFactsheets/utils/apiUtils.js, webapp/app/countryLanding/views/statisticalFactsheets/utils/chartUtils.js, webapp/app/countryLanding/views/statisticalFactsheets/utils/numberUtils.js
=> Custom regions/master

common/userUtils.js, server/db/migration/migrations/20201215090921-fra-audit-remove-country-iso-not-null.js, server/db/migration/migrations/sqls/20201215090921-fra-audit-remove-country-iso-not-null-down.sql, server/db/migration/migrations/sqls/20201215090921-fra-audit-remove-country-iso-not-null-up.sql, server/user/userApi.js, webapp/app/assessment/components/review/review.js, webapp/app/countryLanding/views/messageBoard/messageBoardPanel.js, webapp/app/countryLanding/views/messageBoard/users.js, webapp/app/countryLanding/views/recentActivityView/recentActivityItem.js, webapp/app/user/chat/userChatView.js, webapp/app/user/userManagement/actions.js, webapp/app/user/userManagement/edit/editUserForm.js, webapp/main/basePaths.js
Resolves #643 
- Todo: Resolve how to handle case where admin edits user from Admin view:
- Is column `country_iso` needed in `fra_audit`-table?
=> Changes to user api

server/db/migration/migrations/sqls/20200604164503-statistical-factsheets-view-up.sql, server/statisticalFactsheets/service.js, server/statisticalFactsheets/statisticalFactsheetsRepository.js, webapp/app/countryLanding/views/statisticalFactsheets/ForestAreaPercent/ForestAreaPercent.js, webapp/app/countryLanding/views/statisticalFactsheets/ForestAreaWithinProtectedAreas/ForestAreaWithinProtectedAreas.js, webapp/app/countryLanding/views/statisticalFactsheets/NaturallyRegeneratingForest/NaturallyRegeneratingForest.js, webapp/app/countryLanding/views/statisticalFactsheets/PrimaryForest/PrimaryForest.js, webapp/app/countryLanding/views/statisticalFactsheets/components/table/table.js, webapp/app/countryLanding/views/statisticalFactsheets/utils/apiUtils.js, webapp/app/countryLanding/views/statisticalFactsheets/utils/numberUtils.js
Todo:
- Solve some inconsistency with "Primary forest % of forest area (2020)"
=> statisticalFactsheets: fix inconsistencies

webapp/components/countrySelection/components/CountryListFra/CountryListFra.js
=> CountryListFra: fix area filtering

common/i18n/resources/en/statisticalFactsheets.js, common/i18n/resources/es/statisticalFactsheets.js, common/i18n/resources/fr.js, common/i18n/resources/fr/statisticalFactsheets.js, common/i18n/resources/ru/statisticalFactsheets.js, server/statisticalFactsheets/statisticalFactsheetsRepository.js, webapp/app/countryLanding/views/statisticalFactsheets/ForestAreaWithinProtectedAreas/ForestAreaWithinProtectedAreas.js, webapp/app/countryLanding/views/statisticalFactsheets/ForestOwnership/ForestOwnership.js, webapp/app/countryLanding/views/statisticalFactsheets/PrimaryForest/PrimaryForest.js, webapp/app/countryLanding/views/statisticalFactsheets/components/table/table.js, webapp/app/countryLanding/views/statisticalFactsheets/utils/apiUtils.js, webapp/app/countryLanding/views/statisticalFactsheets/utils/numberUtils.js, webapp/app/countryLanding/views/statisticalFactsheets/utils/propUtils.js
=> statisticalFactsheets: handle null and zero values, show No data

server/country/countryRepository.js, server/db/migration/migrations/20210128091315-update-region-group-fra-fra2020.js, server/db/migration/migrations/sqls/20210128091315-update-region-group-fra-fra2020-down.sql, server/db/migration/migrations/sqls/20210128091315-update-region-group-fra-fra2020-up.sql, webapp/pages/Assessment/AssessmentHome/FraHome/FraHome.js, webapp/store/app/hooks/index.js
=> FraHome: Display button if countryIso is in region_group 1

server/audit/auditRepository.ts
=> auditRepository: fix issue removing user when no countryIso

webapp/app/assessment/components/dataTable/chart/components/dataPoints.tsx
**NOTE: Library is deprecated!!** _Repository archived_
See: https://github.com/caged/d3-tip
Resolves #719
=> dataPoints: fix label data

webapp/app/assessment/components/review/reviewFooter.tsx, webapp/components/verticallyGrowingTextField.tsx
=> verticallyGrowingTextField: refactor component, fix issue with printview

package.json
=> yarn build:copy: copy definitions

server/assessment/service/exportService.ts
filter received countries from query
don't update query (used elsewhere)
=> fix issue bulk download atlantis

webapp/app/assessment/components/dataTable/chart/chartContainer.tsx, webapp/app/assessment/components/dataTable/chart/chartWrapper.tsx, webapp/app/assessment/components/dataTable/chart/components/dataTrend.tsx
=> chartWrapper: fix chart visibility on load

server/api/auth/login.ts, server/serverInit.ts
Tested/testing through deployment to dev instance
Resolves #826
=> Fix issue with login

server/service/email/sendMail.ts
Tested/testing by deployment to dev environment
NPM Module api changed
Resolves #828
=> fix email invitation

.husky/pre-commit, package.json
=> git: update pre-commit hook

webapp/main/basePaths.ts, webapp/pages/PageRoutes/PageRoutes.tsx
=> PageRoutes: add redirect for /:countryIso

webapp/store/app/actions/index.ts
=> app/actions: fix url param

webapp/app/countryLanding/views/statisticalFactsheets/CarbonGrowingStock/CarbonGrowingStock.tsx, webapp/app/countryLanding/views/statisticalFactsheets/ForestArea/ForestArea.tsx, webapp/app/countryLanding/views/statisticalFactsheets/ForestAreaPercent/ForestAreaPercent.tsx, webapp/app/countryLanding/views/statisticalFactsheets/ForestAreaWithinProtectedAreas/ForestAreaWithinProtectedAreas.tsx, webapp/app/countryLanding/views/statisticalFactsheets/ForestOwnership/ForestOwnership.tsx, webapp/app/countryLanding/views/statisticalFactsheets/NaturallyRegeneratingForest/NaturallyRegeneratingForest.tsx, webapp/app/countryLanding/views/statisticalFactsheets/PrimaryDesignatedManagementObjective/PrimaryDesignatedManagementObjective.tsx, webapp/app/countryLanding/views/statisticalFactsheets/PrimaryForest/PrimaryForest.tsx, webapp/app/countryLanding/views/statisticalFactsheets/StatisticalFactsheets.scss, webapp/app/countryLanding/views/statisticalFactsheets/StatisticalFactsheets.tsx, webapp/app/countryLanding/views/statisticalFactsheets/components/table/table.tsx, webapp/app/countryLanding/views/statisticalFactsheets/index.ts, webapp/app/countryLanding/views/statisticalFactsheets/utils/chartUtils.ts
=> Fix dashboard legend labels

server/user/userApi.ts
=> userApi: fix issue with default avatar

common/validateOriginalDataPoint.ts, server/repository/audit/auditRepository.ts, server/repository/odp/create.ts, server/repository/odp/deleteOdp.ts, server/repository/odp/getActualId.ts, server/repository/odp/getAndCheckOdpCountryId.ts, server/repository/odp/getDraftId.ts, server/repository/odp/getOdp.ts, server/repository/odp/getOdpVersionId.ts, server/repository/odp/listOriginalDataPoints.ts, server/repository/odp/markAsActual.ts, server/repository/odp/updateDraftId.ts, server/repository/odpClass/wipeClassData.ts, server/service/odp/create.ts, server/service/odp/deleteDraft.ts, server/service/odp/deleteOdp.ts, server/service/odp/listAndValidateOriginalDataPoints.ts, server/service/odp/persistDraft.ts
=> #5: ODP : Return Types: Service/repository

server/repository/odp/getOdp.ts, server/repository/odp/getOdpVersionId.ts
=> server/repository: getOdpVersionId use pg-promise

webapp/components/Assessment/DataExport/ColumnSelect/ColumnSelect.tsx, webapp/components/Assessment/DataExport/CountrySelect/CountrySelect.tsx, webapp/components/Assessment/DataExport/DataExport.scss, webapp/components/Assessment/DataExport/DataExport.tsx, webapp/components/Assessment/DataExport/ResultsTable/ResultsTable.scss, webapp/components/Assessment/DataExport/ResultsTable/ResultsTable.tsx, webapp/components/Assessment/DataExport/VariableSelect/VariableSelect.tsx, webapp/style/_partials/_spacing.scss
=> Data Export mobile

webapp/components/CountrySelectModal/CountrySelectModal.tsx, webapp/components/CountrySelectModal/CountrySelectModalBody/CountrySelectModalBody.tsx, webapp/components/CountrySelectModal/CountrySelectModalBody/countrySelectModalBody.scss, webapp/components/CountrySelectModal/countrySelectModal.scss
=> Dashboard: Country select mobile

webapp/pages/PageRoutes/PageRoutes.tsx
=> Redirect to pan european when url is /FE/

server/db/migration/migrations/20211011092220-create-original-data-point-table.js, server/db/migration/migrations/sqls/20211011092220-create-original-data-point-table-down.sql, server/db/migration/migrations/sqls/20211011092220-create-original-data-point-table-up.sql
=> Create original_data_point table and populate with existing data

common/api/endpoint/ApiEndPoint.ts, server/api/originalDataPoint/create.ts, server/api/originalDataPoint/get.ts, server/api/originalDataPoint/index.ts, server/api/originalDataPoint/update.ts, server/repository/originalDataPoint/create.ts, server/repository/originalDataPoint/index.ts, server/repository/originalDataPoint/update.ts, server/service/originalDataPoint/create.ts, server/service/originalDataPoint/index.ts, server/service/originalDataPoint/update.ts
Contains also changes for originalDataPoint endpoint and create is now many with body instead of param
=> initial commit for odp/update

core/utils/numbers.ts
=> use inferred return type

core/meta/assessment.ts, server/api/api.ts, server/db/index.ts, server/db/migration/migrations/20211108111343-assessment-schema-update.js, server/db/migration/migrations/sqls/20211108111343-assessment-schema-update-down.sql, server/db/migration/migrations/sqls/20211108111343-assessment-schema-update-up.sql, server/db/schemas.ts, server/repository/assessment/createAssessmentSchema.ts, server/repository/assessment/index.ts, server/service/assessment/createAssessment.ts, server/service/assessment/index.ts
Usage:
```
AssessmentService.createAssessment({
assessment: {
uuid: '6',
props: {
cycles: ['1'],
name: 'fra'
}
}
})
```
Example returns:
=> initial commit for assessment service

server/repository/assessment/createAssessmentSchema.ts, test/integration/index.ts
=> Area tabnles

core/meta/user.ts, core/meta/userAuth.ts, server/db/migration/migrations/20211119092729-create-user-auth.js, server/db/migration/migrations/sqls/20211119092729-create-user-auth-down.sql, server/db/migration/migrations/sqls/20211119092729-create-user-auth-up.sql
=> userRole: add types, migration

tools/dataMigration/index.ts, tools/dataMigration/migrateAreas.ts, tools/dataMigration/migrateMetadata.ts, tools/dataMigration/migrateUsers.ts
=> Migrate users

client/Main.tsx, jsconfig.json, webpack.config.babel.js, webpack.config.babel.test.js
working render for client/
part of #1015
=> initial commit for render white page

client/store/RootState.ts, client/store/user/hooks/index.ts, client/store/user/index.ts, client/store/user/slice.ts, client/store/user/stateType.ts
part of #1015 
- adds rootstate entry for user
- adds hook `userUser`
- adds empty state
=> initial commit for userstate

webapp/components/Assessment/DataExport/DataExport.scss, webapp/components/Assessment/DataExport/DataExport.tsx, webapp/components/Assessment/DataExport/ResultsTable/ResultsTable.tsx, webapp/components/Assessment/DataExport/ResultsTable/Title/Title.tsx, webapp/components/Assessment/DataExport/ResultsTable/useFetchResults.ts, webapp/components/Assessment/DataExport/VariableSelect/VariableSelect.tsx, webapp/store/page/dataExport/dataExportStateType.ts, webapp/store/page/dataExport/hooks/index.ts
DataExport:
Adds multi-variable support
Supports changing unit (variable basis)
Resolves #1066
=> DataExport: Multi-variable support with units

server/controller/user/invite.ts, server/service/index.ts, server/service/mail/index.ts, server/service/mail/mail.ts, server/service/mail/userInvite.ts, test/integration/user/userInvite.test.ts
=> add mailservice

client/components/Header/LanguageSelector/LanguageSelector.tsx, client/pages/PageRoutes/PageRoutes.tsx, client/utils/index.ts, client/utils/url.ts
=> save language

client/pages/Login/Login.tsx, client/pages/Login/LoginForm/LoginForm.tsx, client/pages/Login/LoginForm/index.ts, client/pages/Login/login.scss
=> initial commit for login page

client/pages/Login/Login.tsx, client/pages/Login/LoginForm/LoginForm.tsx, client/pages/Login/ResetPassword/ResetPassword.tsx, client/pages/Login/ResetPassword/index.ts, client/pages/Login/login.scss, i18n/resources/en/login.js
=> reset password

client/pages/Login/Login.tsx, client/pages/Login/LoginForm/LoginForm.tsx, client/pages/Login/LoginForm/index.ts, client/pages/Login/ResetPassword/ResetPassword.tsx, client/pages/Login/ResetPassword/index.ts, client/pages/Login/index.ts, client/pages/Login/login.scss, client/pages/PageRoutes/PageRoutes.tsx, i18n/resources/en/login.js
Master branch for login ui
Plan:
- /login:
- Single page with:
- Email/password field [invite => password2) and login button
- Link to reset password
- Text or hr dividing sections
- Google login button
-  /resetPassword:
- Single page:
- Field email
- Button reset password
=> Login/master: Base branch for login UI

webapp/components/CountrySelect/countrySelect.scss, webapp/main/styles/fraTable.less, webapp/pages/Assessment/assessment.scss
=> fixed windows wrong country selection width, horizontal scrollbar is now global

common/api/endpoint/ApiEndPoint.ts, server/api/auth/config.ts, server/api/auth/googleStrategyVerifyCallback.ts, server/api/auth/index.ts, server/api/auth/localStrategyVerifyCallback.ts, server/api/auth/login.ts, server/api/auth/logout.ts, server/repository/userProvider/index.ts, server/repository/userProvider/read.ts
implements (server):
- logout
- login
NOTE:
Some code left as placeholder for future imeplementation (only commented off for now)
Part of #1035
=> local login, logout

client/store/assessment/actions/getSections.ts, client/store/assessment/actions/initApp.ts, client/store/assessment/slice.ts, client/store/assessment/stateType.ts
populates store with assessment.sections
part of #1092
=> add getSections action

meta/assessment/col.ts, tools/dataMigration/index.ts, tools/dataMigration/migrateData/_createDataViews.ts, tools/dataMigration/migrateData/_repos.ts, tools/dataMigration/migrateData/migrateBasicTablesData.ts, tools/dataMigration/migrateMetadata.ts
- populate row / col tables with variableName / colName
- update data views
=> Add row.props.variableName / col.props.colName

tools/dataMigration/index.ts, tools/dataMigration/migrateData/_getNodeInsertsDegradedForest.ts, tools/dataMigration/migrateData/migrateTablesData.ts, tools/dataMigration/migrateMetadata/index.ts, tools/dataMigration/migrateMetadata/migrateDegradedForest.ts
- Add degraded forest table data migration
=> Data migration: Degraded Forest

client/components/CountrySelect/CountryList/CountryList.tsx, client/hooks/useCountryIso.ts, client/pages/PageRoutes/PageRoutes.tsx, client/store/user/hooks/index.ts
Solves issue where countryIso would return undefined for CountrySelect (which was rendered outside any route)
=> fix user not logged issue

client/components/CountrySelect/CountrySelect.tsx, client/components/Navigation/NavAssessment/Header/Header.scss, client/components/Navigation/NavAssessment/Header/Status/StatusConfirm.scss, client/components/Navigation/NavAssessment/Header/Title/Title.tsx, client/components/Navigation/NavAssessment/Section/Section.scss, client/components/Navigation/NavigationMobile/NavigationMobile.scss, client/pages/Landing/Introduction/AreaSelector/DropdownAreas/DropdownAreas.tsx, client/store/RootState.ts, client/store/rootReducer.ts, client/store/ui/dataLock/hooks/index.ts, client/store/ui/dataLock/index.ts, client/store/ui/dataLock/slice.ts, client/store/ui/dataLock/stateType.ts
=> add data lock

common/api/endpoint/ApiEndPoint.ts, meta/assessment/countryStatus.ts, meta/assessment/index.ts, server/api/assessment/getCountryStatus.ts, server/api/assessment/index.ts, server/controller/assessment/getCountryStatus.ts, server/controller/assessment/index.ts, server/repository/assessment/getCountryStatus.ts, server/repository/assessment/getCreateSchemaDDL.ts, server/repository/assessment/index.ts, tools/dataMigration/index.ts, tools/dataMigration/migrateData/migrateCountryStatus.ts
part of #1119 
`curl localhost:9001/api/country/FIN/assessments/fra/cycles/2025/status`
```{"countryIso":"FIN","status":"editing","deskStudy":false}```
schemas/tables
2025
2020
=> BE: CountryStatus

.github/workflows/heroku-incubator.yml, package.json, server/serverInit.ts, yarn.lock
add WWWHISPER_DISABLE=1 to .env to disable wwhisper locally
=> add wwwhisper / add github action deploy incubator

tools/dataMigration/fraSpecs.ts, tools/dataMigration/migrateData/_repos.ts, tools/dataMigration/migrateData/getNodeInsertsTableWithODP.ts, tools/dataMigration/migrateData/migrateTablesData.ts, tools/dataMigration/migrateMetadata/index.ts
=> Growing Stock tables migration

meta/assessment/col.ts, tools/dataMigration/fraSpecs.ts, tools/dataMigration/getCol.ts, tools/dataMigration/migrateData/_createDataViews.ts, tools/dataMigration/migrateData/_repos.ts, tools/dataMigration/migrateData/migrateTablesData.ts, webapp/sectionSpec/colSpec.ts
=> Sustainable Development tables migration

server/controller/assessment/remove.ts, server/repository/assessment/removeAssessmentSchema.ts, server/repository/assessmentCycle/removeSchema.ts
ddl must be executed with DB, not within a transaction
=> fix assessment ddl

client/basePaths.ts, client/pages/Assessment/Assessment.tsx, client/pages/Assessment/pages/Section/components/SectionHeader/ExtentOfForest/ExtentOfForest.tsx, client/pages/OriginalDataPoint/components/ButtonBar/ButtonBar.tsx, client/pages/OriginalDataPoint/components/OriginalData/OriginalData.tsx, client/store/pages/originalDataPoint/actions/createOriginalDataPoint.ts, client/store/pages/originalDataPoint/actions/deleteOriginalDataPoint.ts, client/store/pages/originalDataPoint/hooks/index.ts, client/store/pages/originalDataPoint/index.ts, client/store/pages/originalDataPoint/slice.ts, client/store/pages/originalDataPoint/stateType.ts, server/api/assessment/createOriginalDataPoint.ts, server/api/assessment/deleteOriginalDataPoint.ts, server/api/assessment/index.ts, server/repository/originalDataPoint/create.ts, tools/dataMigration/migrateData/migrateOdps.ts
=> original data point add and remove

client/components/Toaster/Toaster.scss, client/pages/Login/Invitation/Invitation.tsx, client/pages/Login/Login.tsx, client/pages/Login/LoginForm/LoginForm.tsx, client/pages/Login/ResetPassword/ResetPassword.tsx, client/pages/Login/utils/LoginValidator.tsx, client/store/login/actions/localLogin.ts, i18n/resources/en/login.js, server/api/auth/googleStrategyVerifyCallback.ts
=> various login fixes

client/pages/AssessmentSection/DataTable/utils/index.ts, meta/data/tableDatas.ts, server/repository/cycleData/getTableData.ts, tools/dataMigration/migrateData/_createDataViews.ts, tools/dataMigration/migrateData/migrateTablesData.ts
=> Index by column

.github/workflows/test.js.yml, package.json, server/controller/cycleData/persistNodeValue/expressionEvaluator/binary.ts, server/controller/cycleData/persistNodeValue/expressionEvaluator/context.ts, server/controller/cycleData/persistNodeValue/expressionEvaluator/index.ts, server/controller/cycleData/persistNodeValue/expressionEvaluator/member.ts, server/repository/cycleData/getOriginalDataPointData.ts, test/dataMigration/postDataMigration.ts, tools/dataMigration/fraSpecs.ts, tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/binary.ts, tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/call.ts, tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/compound.ts, tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/context.ts, tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/identifier.ts, tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/index.ts, tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/literal.ts, tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/member.ts, tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/this.ts, tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/unary.ts, tools/dataMigration/migrateMetadata/index.ts, webapp/sectionSpec/rowSpec.ts, yarn.lock
=> migrate calculations table 1d

client/basePaths.ts, client/pages/OriginalDataPoint/OriginalDataPoint.tsx, client/pages/OriginalDataPoint/components/Comments/Comments.tsx, client/pages/OriginalDataPoint/components/OriginalData/OriginalData.tsx, client/store/pages/originalDataPoint/actions/getOriginalDataPoint.ts, common/api/endpoint/ApiEndPoint.ts, meta/assessment/originalDataPoint/originalDataPoint.ts, server/api/assessment/deleteOriginalDataPoint.ts, server/api/assessment/getOdp.ts, server/controller/assessment/getOriginalDataPoint.ts, server/repository/originalDataPoint/getOne.ts, server/repository/originalDataPoint/update.ts, test/integration/assessment/originalDataPoint.ts
=> get odp: deprecate odpId usage and use year+country_iso

client/pages/Geo/GeoMap/GeoMapMenuButton/geoMapMenuButton.scss, client/pages/Geo/GeoMap/GeoMapMenuButton/geoMapMenuButton.tsx, client/pages/Geo/GeoMap/GeoMapMenuButton/index.ts, client/pages/Geo/GeoMap/GeoMapMenuData/geoMapMenuData.scss, client/pages/Geo/GeoMap/GeoMapMenuData/geoMapMenuData.tsx, client/pages/Geo/GeoMap/GeoMapMenuData/index.ts, client/pages/Geo/GeoMap/GeoMapMenuMosaic/geoMapMenuMosaic.scss, client/pages/Geo/GeoMap/GeoMapMenuMosaic/geoMapMenuMosaic.tsx, client/pages/Geo/GeoMap/GeoMapMenuRecipes/geoMapMenuRecipes.scss, client/pages/Geo/GeoMap/GeoMapMenuRecipes/geoMapMenuRecipes.tsx, client/pages/Geo/GeoMap/GeoMapMenuRecipes/index.ts, client/pages/Geo/GeoMap/GeoMapMenuStatistics/geoMapMenuStatistics.scss, client/pages/Geo/GeoMap/GeoMapMenuStatistics/geoMapMenuStatistics.tsx, client/pages/Geo/GeoMap/GeoMapMenuStatistics/index.ts, client/pages/Geo/GeoMapWrapper/GeoMapWrapper.tsx, client/pages/Geo/GeoMapWrapper/geoMapWrapper.scss, client/style/_partials/_config.scss, meta/geo/ui.ts
* Added placeholder buttons for all the geo map menu items
* Separated menu button into its own component
* Added geo map styling variables to partials
=> Added geo map menu buttons

server/controller/cycleData/persistNodeValue/expressionEvaluator/binary.ts, test/dataMigration/postDataMigration.ts, tools/dataMigration/fraSpecs.ts, tools/dataMigration/generateMetaCache/expressionEvaluator/evalDependencies/member.ts
=> Migrate calculations section 8

common/api/endpoint/ApiEndPoint.ts, server/api/definitions/index.ts
=> remove unused api

meta/assessment/cols.ts, server/db/db.ts, server/repository/assessment/assessment/getCreateSchemaDDL.ts, server/repository/assessmentCycle/data/getOriginalDataPointData.ts, tools/dataMigration/index.ts, tools/dataMigration/migrateData/migrateTablesData.ts
=> Fix odp forestArea variable name / Migrate data all cycles

client/pages/AssessmentSection/DataTable/Table/Table.tsx
=> Fix tooltip on odp

meta/assessment/activityLog.ts, server/controller/assessment/create.ts, server/controller/assessment/createCycle.ts, server/controller/assessment/createOriginalDataPoint.ts, server/controller/assessment/removeOriginalDataPoint.ts, server/controller/assessment/updateCountry.ts, server/controller/assessment/updateOriginalDataPoint.ts, server/controller/cycleData/persistNodeValue/createOrUpdateNode.ts, server/controller/messageCenter/addMessage.ts, server/controller/user/invite.ts, server/repository/assessment/activityLog/insertActivityLog.ts, server/repository/assessment/assessment/getCreateSchemaDDL.ts, server/repository/public/userRole/create.ts, test/integration/integration.test.ts, test/integration/user/userInvite.ts
=> ActivityLog: add cycle_uuid, replace schemaName with cycle, assessment

client/components/CountrySelect/countrySelect.scss
=> countrySelect: fix font family

client/pages/AssessmentSection/DataTable/Chart/chartContainer.tsx, client/pages/AssessmentSection/DataTable/Chart/components/xAxis.tsx
=> datatable/Chart: Fix issues with chart:

client/components/MessageCenter/Topic/Message/Message.tsx, client/components/MessageCenter/Topic/Topic.scss, client/components/MessageCenter/Topic/Topic.tsx, client/pages/PageRoutes/PageRoutes.tsx, client/service/socket/index.ts, client/service/socket/socketClient.ts, client/store/axiosErrorMiddleware.ts, client/store/ui/messageCenter/actions/index.ts, client/store/ui/messageCenter/actions/postMessage.ts, client/store/ui/messageCenter/slice.ts, meta/socket/sockets.ts, package.json, server/api/assessment/getSections.ts, server/api/auth/login.ts, server/api/messageCenter/addMessage.ts, server/controller/messageCenter/addMessage.ts, server/index.ts, server/repository/assessmentCycle/message/create.ts, server/serverInit.ts, server/service/socket/index.ts, server/service/socket/socketService.ts, test/dataMigration/jest.config.js, test/integration/messageCenter/messageCenter.ts, webpack.config.babel.js, yarn.lock
=> Websocket review 

client/store/pages/assessmentSection/hooks/index.ts
Add nullcheck for tableData
Resolves #1286
(Unable to replicate)
=> Nullcheck tableData

client/components/ButtonTableExport/ButtonTableExport.scss, client/components/ButtonTableExport/ButtonTableExport.tsx, client/pages/AssessmentSection/DataTable/Table/Row/RowData/RowData.tsx, client/pages/AssessmentSection/DataTable/Table/Table.tsx, client/pages/OriginalDataPoint/components/DataSources/DataSources.tsx, client/pages/OriginalDataPoint/components/ExtentOfForest/ExtentOfForestRow.tsx, client/pages/OriginalDataPoint/components/ForestCharacteristics/ForestCharacteristicsPlantationRow.tsx, client/pages/OriginalDataPoint/components/ForestCharacteristics/ForestCharacteristicsRow.tsx, client/pages/OriginalDataPoint/components/NationalClasses/NationalClass/NationalClass.tsx, client/styles/fraTable.scss
=> fixed review indicator and export button alignments

server/service/estimates/estimationEngine.test.ts, server/service/estimates/estimationEngine.ts, test/deprecated_unit/estimationEngineTest.ts
=> Estimation engine/dataformat

server/repository/assessment/assessment/getCreateSchemaDDL.ts, server/repository/assessmentCycle/cycle/create.ts, server/repository/assessmentCycle/data/getOriginalDataPointData.ts, tools/dataMigration/index.ts, tools/dataMigration/migrateData/_createDataViews.ts, tools/dataMigration/migrateData/migrateOdps.ts, tools/dataMigration/migrateData/migrateTablesData.ts, tools/dataMigration/migrateMetadata/migrateTableWithODP.ts
Resolves #1304
and points 1/2 of #1306
=> fix ODP calculated node values

client/pages/AssessmentSection/DataTable/DataTable.tsx, client/pages/AssessmentSection/DataTable/GenerateValues/FieldsOption/FieldsOption.tsx, client/pages/AssessmentSection/DataTable/GenerateValues/FieldsOption/index.ts, client/pages/AssessmentSection/DataTable/GenerateValues/GenerateValues.scss, client/pages/AssessmentSection/DataTable/GenerateValues/GenerateValues.tsx, client/pages/AssessmentSection/DataTable/GenerateValues/field.ts, client/pages/AssessmentSection/DataTable/GenerateValues/index.ts, client/pages/AssessmentSection/DataTable/GenerateValues/method.ts, client/pages/AssessmentSection/DataTable/GenerateValues/useGenerateValules.ts
=> Estimation engine/UI

server/controller/cycleData/getTableData.ts, test/dataMigration/steps/deleteWrongCalculatedNodes.ts, test/dataMigration/steps/updateCalculatedNodes/getClimaticDomainValues.ts, test/dataMigration/steps/updateCalculatedNodes/updateCalculatedNodes.ts, tools/dataMigration/migrateMetadata/index.ts, tools/dataMigration/migrateMetadata/migrateClimaticDomain.ts
=> migrate climatic domain table metadata and data

client/pages/Assessment/Assessment.tsx, client/pages/Assessment/SectionWrapper/SectionWrapper.tsx, client/pages/Assessment/SectionWrapper/index.ts, client/pages/AssessmentSection/DataTable/Chart/chartWrapper.tsx, client/pages/PageRoutes/useTheme.ts, client/utils/dom.ts
=> SectionPage: scroll to top when navigating to new page

client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Cell.tsx, client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/useClassName.ts, client/pages/AssessmentSection/DataTable/Table/Row/RowData/RowData.tsx, client/pages/AssessmentSection/DataTable/Table/Table.tsx, meta/assessment/cols.ts, tools/dataMigration/fraSpecs.ts
=> fix table data rows/cols style

client/components/MessageCenter/Topic/Topic.scss, client/components/MessageCenter/Topic/Topic.tsx, client/store/ui/messageCenter/slice.ts, i18n/resources/en.js, meta/messageCenter/messageTopic.ts, server/api/assessment/getReviewSummary.ts, server/repository/assessmentCycle/messageTopicUser/getOdpReviewStatus.ts, server/repository/assessmentCycle/messageTopicUser/getReviewStatus.ts, server/repository/assessmentCycle/messageTopicUser/getReviewSummary.ts
=> some review fixes

client/pages/AssessmentSection/DataTable/Chart/components/dataPath.tsx, client/pages/AssessmentSection/DataTable/DataTable.tsx, client/pages/OriginalDataPoint/components/NationalClasses/NationalClass/NationalClass.tsx, client/store/pages/originalDataPoint/actions/createOriginalDataPoint.ts
=> Fix National Classes, GenerateValues, random crash

client/basePaths.ts, client/components/CountrySelect/CountryList/CountryList.tsx, client/components/CountrySelect/CountryList/CountryListDownload/CountryListDownload.tsx, client/components/CountrySelect/CountryList/CountryListRoleSection/CountryListRoleSection.tsx, client/components/CountrySelect/CountryList/CountryListRow/CountryListRow.tsx, client/components/CountrySelect/CountryList/countryList.scss, client/components/CountrySelect/CountryList/hooks/useUserCountryISOs.tsx, client/components/CountrySelect/CountrySelect.tsx, client/components/CountrySelect/utils/checkMatch.ts, client/store/assessment/hooks/index.ts, client/store/assessment/index.ts, meta/area/areas.ts, meta/area/country.ts, meta/area/region.ts, server/api/init/init.ts, server/repository/assessmentCycle/country/getMany.ts
=> Country Select with assessment information and CSV download

client/components/CountrySelectModal/CountrySelectModal.tsx, client/components/CountrySelectModal/CountrySelectModalBody/CountrySelectModalBody.tsx, client/components/CountrySelectModal/CountrySelectModalBody/countrySelectModalBody.scss, client/components/CountrySelectModal/CountrySelectModalBody/index.ts, client/components/CountrySelectModal/countrySelectModal.scss, client/components/CountrySelectModal/index.ts, client/pages/AssessmentHome/AssessmentHome.scss, client/pages/AssessmentHome/FraHome/CountrySelector/CountrySelector.tsx, client/pages/AssessmentHome/FraHome/CountrySelector/index.ts, client/pages/AssessmentHome/FraHome/FraHome.tsx, client/pages/AssessmentHome/FraHome/SelectedCountries/SelectedCountries.tsx, client/pages/AssessmentHome/FraHome/SelectedCountries/index.ts, client/store/RootState.ts, client/store/assessment/hooks/index.ts, client/store/rootReducer.ts, client/store/ui/home/hooks.ts, client/store/ui/home/slice.ts, client/store/ui/home/stateType.ts, meta/area/areas.ts
=> Initial commit for Country Selection

client/components/Navigation/NavAssessment/Header/Title/CycleSwitcher.tsx, client/components/Navigation/NavAssessment/Header/Title/Title.tsx, client/pages/Assessment/SectionWrapper/SectionWrapper.tsx
=> Cycle Switcher

common/i18n/resources/en/area.js, webapp/app/countryLanding/views/manageCollaboratorsView.tsx
=> Turkey rebrand

client/components/Navigation/NavAssessment/Header/Title/CycleSwitcher.tsx
=> CycleSwitcher/canSwitchCycle: check user cycles

common/i18n/resources/es/area.js, common/i18n/resources/fr/area.js
=> Turkey rebrand again

webapp/components/CountrySelect/utils/checkMatch.ts
=> string normalisation for accented chars

server/controller/cycleData/persistNodeValue/expressionEvaluator/functions/index.ts, server/controller/cycleData/persistNodeValue/expressionEvaluator/functions/validatorEqualToTotalGrowingStock.ts, tools/dataMigration/fraSpecs.ts, webapp/sectionSpec/fra/growingStock/growingStockValidatorState.ts
=> migrate validations section 2

client/components/CountrySelect/CountryList/CountryListRoleSection/CountryListRoleSection.tsx, client/components/InviteUserForm/InviteUserForm.scss, client/components/InviteUserForm/InviteUserForm.tsx, client/components/UserList/UserList.tsx, client/pages/AssessmentHome/FraHome/Collaborators/Collaborators.tsx, meta/user/authorizer.ts, server/api/user/index.ts, server/middleware/auth.ts, server/service/mail/userInvite.ts
close #1355
**requireInviteUser**: only users getRolesAllowedToEdit
**requireViewUsers**: admin and users who have a role for that country/assessment/cycle (doesn't matter if a cycle is published or not)
=> added requireInviteUser and requireViewUsers

client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/Cell.tsx, client/pages/AssessmentSection/DataTable/Table/Row/RowData/Cell/useOnChange.ts, client/pages/Dashboard/CarbonGrowingStock/CarbonGrowingStock.tsx, client/pages/Dashboard/Dashboard.tsx, client/pages/Dashboard/ForestArea/ForestArea.tsx, client/pages/Dashboard/ForestAreaPercent/ForestAreaPercent.tsx, client/pages/Dashboard/ForestAreaWithinProtectedAreas/ForestAreaWithinProtectedAreas.tsx, client/pages/Dashboard/ForestOwnership/ForestOwnership.tsx, client/pages/Dashboard/NaturallyRegeneratingForest/NaturallyRegeneratingForest.tsx, client/pages/Dashboard/PrimaryForest/PrimaryForest.tsx, client/pages/Dashboard/components/Table/Table.tsx, meta/data/tableDatas.ts, server/repository/assessmentCycle/data/getAggregatedTableData.ts
Part of #1333
Part of #1353 (Regions)
=> Add global dashboard, use TableDatas to extract NodeValue

client/pages/Dashboard/CarbonGrowingStock/CarbonGrowingStock.tsx, client/pages/Dashboard/PrimaryDesignatedManagementObjective/PrimaryDesignatedManagementObjective.tsx, client/pages/Dashboard/components/Table/Table.tsx, meta/assessment/table.ts
=> Dashboard: Calculate country values for CarbonGrowingStock table

client/components/Navigation/NavigationDesktop/NavigationDesktop.tsx, client/pages/Assessment/Assessment.tsx, client/pages/AssessmentDataDownload/dataDownload.scss, client/pages/AssessmentDataDownload/index.tsx, client/pages/AssessmentDataDownload/resources.ts, common/api/endpoint/ApiEndPoint.ts, server/api/file/getDataDownloadFile.ts, server/api/file/index.ts
Resolves #1377 
- Leaves out 'bulkDownload'
=> DataDownload: Initial commit

client/pages/Dashboard/components/Table/Table.tsx
=> Handle NaN string value in table

server/controller/cycleData/persistNodeValue/expressionEvaluator/functions/index.ts, server/controller/cycleData/persistNodeValue/expressionEvaluator/functions/validatorForestAreaComparedTo2015.ts, test/dataMigration/postDataMigration.ts, test/dataMigration/steps/validateNodes/validateNodes.ts, tools/dataMigration/fraSpecs.ts, tools/dataMigration/generateMetaCache/index.ts, webapp/sectionSpec/fra/extentOfForest/extentOfForestValidatorState.ts
=> Add validatorForestAreaComparedTo2015

client/pages/AssessmentSection/DataTable/DataTable.tsx, client/pages/AssessmentSection/DataTable/utils/index.ts, client/store/pages/assessmentSection/hooks/index.ts
=> Fix rendering tables with no data

client/components/CountrySelect/CountrySelect.tsx, common/countryRole.ts, tools/dataMigration/fraSpecs.ts
=> Fix forest ownership calc formula

server/db/migration/migrations/20220727095342-move-descriptions-legacy.js, server/db/migration/migrations/sqls/20220727095342-move-descriptions-legacy-down.sql, server/db/migration/migrations/sqls/20220727095342-move-descriptions-legacy-up.sql, server/repository/assessment/assessment/getCreateSchemaDDL.ts, test/dataMigration/postDataMigration.ts, test/dataMigration/steps/migrateDescriptions.ts
=> Migrate descriptions

client/pages/Dashboard/ForestArea/ForestArea.tsx, client/pages/Dashboard/NaturallyRegeneratingForest/NaturallyRegeneratingForest.tsx
=> Fix xAxis issue

common/api/endpoint/ApiEndPoint.ts, meta/assessment/commentableDescription.ts, server/api/assessment/getCommentableDescription.ts, server/api/assessment/index.ts, server/controller/cycleData/index.ts, server/repository/assessmentCycle/descriptions/getOneOrNone.ts, server/repository/assessmentCycle/descriptions/index.ts
=> Commentable Description API

client/components/Navigation/Navigation.tsx, client/pages/Assessment/Assessment.tsx, package.json, yarn.lock
=> Fix Sections fetch on cycle change

client/pages/AssessmentSection/Descriptions/Description/Description.tsx, client/store/pages/assessmentSection/actions/updateDescription.ts, client/store/pages/assessmentSection/slice.ts, meta/assessment/activityLog.ts, server/api/assessment/index.ts, server/api/assessment/updateDescription.ts, server/api/assessment/upsertDescription.ts, server/controller/cycleData/index.ts, server/controller/cycleData/upsertDescription.ts, server/repository/assessmentCycle/descriptions/index.ts, server/repository/assessmentCycle/descriptions/update.ts, server/repository/assessmentCycle/descriptions/upsert.ts
=> descriptions: Implement description edit

client/pages/OriginalDataPoint/OriginalDataPoint.tsx, client/pages/OriginalDataPoint/components/Comments/CommentsEditor.tsx
=> originalDataPoints: Comments

client/pages/AssessmentSection/DataTable/Table/Row/RowData/RowData.tsx, client/pages/AssessmentSection/DataTable/Table/parseTable.ts, client/pages/AssessmentSection/Descriptions/Descriptions.tsx, client/pages/AssessmentSection/SectionHeader/ForestCharacteristics/ForestCharacteristics.tsx, client/store/pages/assessmentSection/hooks/index.ts, client/store/pages/assessmentSection/index.ts, meta/assessment/description.ts, tools/dataMigration/migrateMetadata/getSection.ts
Resolves #1436 
https://user-images.githubusercontent.com/1138156/183724210-7a64d099-4d08-43ec-adde-fcbe54cf10ff.mov
=> Add conditional descriptions rendering

client/pages/PageRoutes/PageRoutes.tsx
=> Add routing for print/tables

client/pages/AssessmentHome/FraHome/ButtonDownloadDashboard/ButtonDownloadDashboard.tsx, client/pages/Login/Invitation/Invitation.tsx, client/store/assessment/actions/initApp.ts, client/store/assessment/actions/updateCountry.ts, client/store/login/actions/createResetPassword.ts, client/store/login/actions/localLogin.ts, common/api/endpoint/ApiEndPoint.ts, meta/api/request/auth/login.ts, meta/api/request/index.ts, meta/api/request/init/init.ts, server/api/api.ts, server/api/area/index.ts, server/api/area/postCountry.ts, server/api/assessment/index.ts, server/api/auth/googleStrategyVerifyCallback.ts, server/api/auth/index.ts, server/api/auth/localStrategyVerifyCallback.ts, server/api/auth/login.ts, server/api/definitions/index.ts, server/api/file/index.ts, server/api/init/index.ts, server/api/init/init.ts
init, definitions, Area Auth, File
=> Initial commit for refactor api

client/pages/AssessmentSection/DataTable/GenerateValues/useGenerateValules.ts, client/pages/Dashboard/hooks/useDashboardData.ts, client/pages/DataExport/ResultsTable/useFetchResults.ts, client/store/pages/assessmentSection/actions/getTableData.ts, client/store/pages/assessmentSection/actions/postEstimate.ts, common/api/endpoint/ApiEndPoint.ts, meta/api/request/cycleData/table.ts, meta/api/request/index.ts, server/api/assessment/index.ts, server/api/cycleData/index.ts, server/api/cycleData/table/getTableData.ts, server/api/cycleData/table/postEstimation.ts, server/middleware/auth.ts
=> Refactor cycleData/table endpoint

client/components/MessageCenter/Topic/Message/Message.tsx, client/pages/AssessmentHome/FraHome/CountryMessageBoard/MessageBoardUsers.tsx, client/pages/Dashboard/hooks/useDashboardData.ts, client/pages/Login/Invitation/Invitation.tsx, client/pages/Login/LoginForm/LoginForm.tsx, client/store/login/actions/acceptInvitation.ts, client/store/login/actions/fetchUserByInvitation.ts, client/store/userManagement/actions/getUserToEdit.ts, client/store/userManagement/actions/getUsers.ts, client/store/userManagement/actions/inviteUser.ts, client/store/userManagement/actions/removeInvitation.ts, client/store/userManagement/actions/sendInvitationEmail.ts, client/store/userManagement/actions/updateUser.ts, common/api/endpoint/ApiEndPoint.ts, meta/user/users.ts, server/api/user/acceptInvitation.ts, server/api/user/getInvitation.ts, server/api/user/index.ts, server/api/user/invite.ts, server/api/user/removeInvitation.ts, server/api/user/sendInvitationEmail.ts, server/api/user/updateUser.ts
=> refactor user endpoint

meta/assessment/activityLog.ts, meta/assessment/activityLogs.ts, server/api/area/postCountry.ts, server/api/messageCenter/addMessage.ts, server/api/messageCenter/markMessageDeleted.ts, server/api/messageCenter/resolveTopic.ts, server/controller/area/updateCountry.ts, server/controller/messageCenter/addMessage.ts, server/controller/messageCenter/markMessageDeleted.ts, server/controller/messageCenter/updateTopicStatus.ts, server/controller/user/update.ts, server/repository/assessment/activityLog/getCycleDataActivities.ts, test/integration/messageCenter/messageCenter.ts
=> missing activities (change status and comment)

src/client/components/Header/LanguageSelector/LanguageSelector.tsx, src/client/store/assessment/actions/initApp.ts
Resolves #1485 
https://user-images.githubusercontent.com/5508251/188627127-315c6b94-7144-4c89-b685-edb10f3545fa.mov
=> Fix user language selection

src/server/db/migration/migrations/20220914110105-move-repository-table-to-legacy.js, src/server/db/migration/migrations/sqls/20220914110105-move-repository-table-to-legacy-down.sql, src/server/db/migration/migrations/sqls/20220914110105-move-repository-table-to-legacy-up.sql, tools/dataMigration/index.ts, tools/dataMigration/migrateRepository.ts
=> repository migration

src/test/dataMigration/postDataMigration.ts, src/test/dataMigration/steps/metadataFix/metadataFix.ts
=> fix calculated columns 2025

src/client/pages/AssessmentPrint/FraPrint/ContactPersons/ContactPersons.tsx, src/client/store/userManagement/actions/getUsers.ts, src/server/api/user/getMany.ts, src/server/utils/processEnv.ts
close #1505
- The one with 1a is a user with status = active invited as a Collaborator for that Country and the Table/Section 1a
- The one with None is a user with status = pendingInvitation,  invited as a Collaborator for that Country and without any Table/Section permissions
The previous condition was:
- User status must be active
- User must not be a Reviewer
- User must have assigned a Section
In the new condition I have removed the third point
=> show invited users who doesn't have yet accepted the invitation
